baseURL: "https://www.lunulata.io/"
languageCode: "en-us"
title: "lunulata.io"
theme: "hugo-flex"

params:
  color: ForestGreen
  width: 52rem
  footer: >
    <p><a href="https://github.com/kressi/">https://github.com/kressi/</a></p>
    <p><a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">
      <img src="/img/cc-by-nc-sa.png" alt="CC BY-NC-SA">
    </a></p>
  summaries: false
  divider: '\2015\2015'

menu:
  nav:
  - name: about
    url: about/
    weight: 1
