baseURL: "https://www.lunulata.io/"
languageCode: "en-us"
title: "lunulata.io"
theme: "hugo-flex"

params:
  color: ForestGreen
  width: 52rem
  footer: '<a href="https://github.com/kressi/">https://github.com/kressi/</a>'
  summaries: false
  divider: '\2015\2015'

menu:
  nav:
  - name: about
    url: about/
    weight: 1
  - name: posts
    url: posts/
    weight: 2
