baseURL: "https://www.lunulata.io/"
languageCode: "en-us"
title: "lunulata.io"
theme: "hugo-flex"

params:
  color: ForestGreen
  width: 52rem
  footer: >
    <a href="https://github.com/kressi/"><img src="/images/github-32.svg" alt="Github"></a>
    <a href="mailto:lunulata@gmx.net"><img src="/images/mail-32.svg" alt="Email"></a>
  summaries: false
  divider: '\2015\2015'

menu:
  nav:
  - name: about
    url: about/
    weight: 1
